In [14]:
import numpy as np

In [15]:
# 1.1.2

mat_a = np.matrix([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
mat_b = np.matrix([[1, 2, 1], [0, 1, 2], [3, 1, 1]])

print('AB - BA =')
print(mat_a * mat_b - mat_b * mat_a)

AB - BA =
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [16]:
# 1.2.2
mat_a = np.matrix([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])

print('A^2 =')
print(mat_a * mat_a)

A^2 =
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [17]:
# 1.3.2
mat_a = np.matrix([[5, 8, -4], [6, 9, -5], [4, 7, -3]])
mat_b = np.matrix([[3, 2, 5], [4, -1, 3], [9, 6, 5]])

mat_c = mat_a * mat_b
print('AB =')
print(mat_c)


AB =
[[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [18]:
# 1.4.2
mat_a = np.matrix([[0, 2, 0], [3, 4, 5], [6, 7, 8]])
mat_a_det = np.linalg.det(mat_a)

print(f'det(A) = {mat_a_det:.2f}')

det(A) = 12.00


In [19]:
# 1.5.2
mat_a = np.matrix([[2, 3, 4, 1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])
mat_a_det = np.linalg.det(mat_a)

print(f'det(A) = {mat_a_det:.2f}')

det(A) = -160.00


In [20]:
# 1.6.2
mat_a = np.matrix([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
mat_a_inv = np.linalg.inv(mat_a)

print('A^-1 =')
print(mat_a_inv)

A^-1 =
[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [28]:
# 1.7.2
mat_a = np.matrix([[1, -1, 3, 4], [0, -1, 2, 1], [1, 1, -1, 2], [2, 3, -5, 3]])
mat_a_rank = np.linalg.matrix_rank(mat_a)

print(f'rank(A) = {mat_a_rank}')

rank(A) = 3


In [22]:
# 1.8.2
def kramer(A, B):
    a_det = np.linalg.det(A)
    
    if a_det != 0:
        x_mat = np.matrix(A)
        x_mat[:, 0] = B
        y_mat = np.matrix(A)
        y_mat[:, 1] = B
        z_mat = np.matrix(A)
        z_mat[:, 2] = B

        x = np.linalg.det(x_mat) / a_det
        y = np.linalg.det(y_mat) / a_det
        z = np.linalg.det(z_mat) / a_det

        return x, y, z
    else:
        return None

mat_a = np.matrix([[2, -1, 1], [3, 2, 2], [1, -2, 1]])
mat_b = np.matrix([[2], [-2], [1]])

x, y, z = kramer(mat_a, mat_b)
print(f'x= {x: .2f}\ny= {y: .2f}\nz= {z: .2f}')

x=  2.00
y= -1.00
z= -3.00


In [29]:
# 2.6
import random

n = int(input('Enter n: '))
m = int(input('Enter m: '))

mat_a = np.matrix([[random.randint(-10, 10) for j in range(m)] for i in range(n)])

print('A =')
print(mat_a)

avg_rows = np.mean(mat_a, axis=1)
min_row = np.argmin(avg_rows)
print(f'Row with the lowest average: {min_row+1}')
print(f'Average: {avg_rows[min_row, 0]:.2f}')

A =
[[ -5   2  -8   3   7   0   5   0  -5]
 [  3  -3  10  -7  -6  10   5  -6  -7]
 [ 10   8  -9  -6   1   0   7   5   9]
 [  0  -3  -1   6   2   0  -4   1   4]
 [  1  -8   1   8   9  -1  -8   5   6]
 [ -1  -5  -1   4  -4  -2   7   8   5]
 [ -5   0  -6  10  -4 -10   2  -1   8]
 [ -8   3  -7  -9   0  -8   8  -5 -10]
 [  7   8   6   6  -6   6  -3   8  -2]]
Row with the lowest average: 8
Average: -4.00
